services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - path: .
          action: sync+restart
          target: /usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
